language: php

dist: bionic

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.4

env:
  - PYGMENTS_VERSION=2.4.0
  - PYGMENTS_VERSION=2.4.1
  - PYGMENTS_VERSION=2.4.2
  - PYGMENTS_VERSION=2.5.1
  - PYGMENTS_VERSION=2.5.2
  - PYGMENTS_VERSION=2.6.0
  - PYGMENTS_VERSION=2.6.1
  - PYGMENTS_VERSION=2.7.0
  - PYGMENTS_VERSION=2.7.1

addons:
  apt:
    packages:
      - python3-pip

install:
  - travis_retry pip3 install Pygments==$PYGMENTS_VERSION
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/coverage.xml
